# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

covmat_c <- function(Xt, mu, u) {
    .Call(`_dFCaHSMM_covmat_c`, Xt, mu, u)
}

standardize_rows_cpp <- function(A) {
    .Call(`_dFCaHSMM_standardize_rows_cpp`, A)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE, chol = FALSE) {
    .Call(`_dFCaHSMM_dmvnrm_arma`, x, mean, sigma, logd, chol)
}

logvec_c <- function(x) {
    .Call(`_dFCaHSMM_logvec_c`, x)
}

logsumexp_cpp <- function(X) {
    .Call(`_dFCaHSMM_logsumexp_cpp`, X)
}

get_locations <- function(B) {
    .Call(`_dFCaHSMM_get_locations`, B)
}

vec2params_covar <- function(params_vec, num_states, Z_n_cols, betahat) {
    invisible(.Call(`_dFCaHSMM_vec2params_covar`, params_vec, num_states, Z_n_cols, betahat))
}

params2vec_covar <- function(beta, num_states, Z_n_cols) {
    .Call(`_dFCaHSMM_params2vec_covar`, beta, num_states, Z_n_cols)
}

get_emission_distribution <- function(Xt, u_all, m, SampCov, mu_hat_next, Sigma_hat_next, Omega_hat_next) {
    invisible(.Call(`_dFCaHSMM_get_emission_distribution`, Xt, u_all, m, SampCov, mu_hat_next, Sigma_hat_next, Omega_hat_next))
}

forward_backward_hsmm_cpp <- function(Xt, m, B, mu, root, delta, chol = FALSE) {
    .Call(`_dFCaHSMM_forward_backward_hsmm_cpp`, Xt, m, B, mu, root, delta, chol)
}

pk_cpp <- function(r, lambda, tau = 1L) {
    .Call(`_dFCaHSMM_pk_cpp`, r, lambda, tau)
}

Fk_cpp <- function(r, lambda, tau = 1L) {
    .Call(`_dFCaHSMM_Fk_cpp`, r, lambda, tau)
}

ck_cpp <- function(r, lambda, tau = 1L, verbose = 0L) {
    .Call(`_dFCaHSMM_ck_cpp`, r, lambda, tau, verbose)
}

grad_ck_cpp <- function(r, lambda, tau = 1L, verbose = 0L) {
    .Call(`_dFCaHSMM_grad_ck_cpp`, r, lambda, tau, verbose)
}

create_Bij_cpp <- function(lambda, aij, mi, mj, tau = 1L) {
    .Call(`_dFCaHSMM_create_Bij_cpp`, lambda, aij, mi, mj, tau)
}

create_gradBij_cpp <- function(lambda, mi, mj, tau = 1L) {
    .Call(`_dFCaHSMM_create_gradBij_cpp`, lambda, mi, mj, tau)
}

create_Bii_cpp <- function(lambda, mi, tau = 1L, verbose = 0L) {
    .Call(`_dFCaHSMM_create_Bii_cpp`, lambda, mi, tau, verbose)
}

create_gradBii_cpp <- function(lambda, mi, tau = 1L, verbose = 0L) {
    .Call(`_dFCaHSMM_create_gradBii_cpp`, lambda, mi, tau, verbose)
}

create_B_cpp <- function(lambda, m, A, tau = 1L, verbose = 0L) {
    .Call(`_dFCaHSMM_create_B_cpp`, lambda, m, A, tau, verbose)
}

create_gradB_cpp <- function(lambda, m, tau = 1L, verbose = 0L) {
    .Call(`_dFCaHSMM_create_gradB_cpp`, lambda, m, tau, verbose)
}

get_lambdan <- function(Zn, beta) {
    .Call(`_dFCaHSMM_get_lambdan`, Zn, beta)
}

term2_covar_cpp <- function(params_vec, Amat, Z, m, sum_t_vjk, verbose = 0L) {
    .Call(`_dFCaHSMM_term2_covar_cpp`, params_vec, Amat, Z, m, sum_t_vjk, verbose)
}

grad_term2_cpp <- function(params_vec, Amat, Z, m, sum_t_vjk) {
    .Call(`_dFCaHSMM_grad_term2_cpp`, params_vec, Amat, Z, m, sum_t_vjk)
}

optim_covar_rcpp <- function(params_vec, Amat, Z, m, sum_t_vjk) {
    .Call(`_dFCaHSMM_optim_covar_rcpp`, params_vec, Amat, Z, m, sum_t_vjk)
}

em_estep_covar <- function(Xt, Z, m, beta, A, mu, Sigma, delta, iter, lalpha, lbeta, llk, sum_t_vjk, u_all) {
    invisible(.Call(`_dFCaHSMM_em_estep_covar`, Xt, Z, m, beta, A, mu, Sigma, delta, iter, lalpha, lbeta, llk, sum_t_vjk, u_all))
}

get_Ahat <- function(sum_t_vjk, m, num_states) {
    .Call(`_dFCaHSMM_get_Ahat`, sum_t_vjk, m, num_states)
}

em_mstep_covar <- function(Xt, Z, m, sum_t_vjk, u_all, beta_hat, beta_hat_next, A_hat_next, delta_hat_next, mu_hat_next, SampCov, Sigma_hat_next, Omega_hat_next, refit) {
    invisible(.Call(`_dFCaHSMM_em_mstep_covar`, Xt, Z, m, sum_t_vjk, u_all, beta_hat, beta_hat_next, A_hat_next, delta_hat_next, mu_hat_next, SampCov, Sigma_hat_next, Omega_hat_next, refit))
}

hsmm_cpp <- function(Xt, Z, A_init, mu_init, Sigma_init, beta_init, m, maxiter = 10000L, tol = 1e-4, verbose = 1L, refit = 0L) {
    .Call(`_dFCaHSMM_hsmm_cpp`, Xt, Z, A_init, mu_init, Sigma_init, beta_init, m, maxiter, tol, verbose, refit)
}

